name: Update Profile Stats SVG

on:
  schedule:
    - cron: '0 */2 * * *' # Se ejecuta cada 2 horas
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Execute script for language stats
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: node generate-stats.js

      - name: Download Streak Stats SVG
        run: |
          # Descarga a un archivo temporal y solo reemplaza si la petición fue exitosa (código 200)
          curl -s -f "https://streak-stats.demolab.com/?user=IgnacioAcena23&theme=tokyonight&hide_border=true" -o streak.svg.tmp && mv streak.svg.tmp streak.svg || echo "No se pudo actualizar streak.svg, conservando archivo previo."

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add languages.svg streak.svg
          git diff --staged --quiet || (git commit -m "build: update profile stats [skip ci]" && git push)
